
<html>

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body>

	<p>
		Thank you for registration on <b>http://<?php echo $_SERVER['HTTP_HOST']; ?></b>. 
		For activation your account click please this  
		<a href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/email/confirmation/<?php echo $this -> user -> secureHash; ?>">link</a>. 
	</p>
	<p>
		if you not registering no this web site then ignore please this message.
	</p>
	<p>
		Administrations of <b>http://<?php echo $_SERVER['HTTP_HOST']; ?></b>
	</p>

</body>

</html>
