<!-- Base page -->
<div class="row">
	
	<?php
	
		echo
		$this -> partial(
			'widgets/navigation.phtml', 
			//- Params -//
			array(
				'label'	=> 'Actions', 
				'items'	=> array(
					array(
						'label'	=> 'Forgot password', 
						'uri'	=> '/'
					), 
					array(
						'label'	=> 'Registration', 
						'uri'	=> '/registration'
					)
				)
			)
		);
	
	?>
	
	 <div class="span9">
		 <div class="content">
			 <div class="article">     
			 
			 	<h1><?= $this -> translate( 'Forgot' ); ?></h1>
			 
			 	<div>
			 		<?= $this -> form; ?>
			 		<!--<form action = "/forgot" method = "post">
					
						<label>Enter your email</label>
						<input type = "email" name = "email" />
						<input type = "submit" value = "<?= $this -> translate( 'Send' ); ?>" />
					
					</form>-->
				</div>
				
			 </div>
		</div>
	</div>
 
</div>