<!-- Base page -->
<div class="row">
	
	<?php
	
		echo
		$this -> partial(
			'widgets/navigation.phtml', 
			//- Params -//
			array(
				'label'	=> 'Journal', 
				'items'	=> array(
					array(
						'label'	=> 'List', 
						'uri'	=> '/journals'
					), 
					array(
						'label'	=> 'Add', 
						'uri'	=> '/journal/add'
					), 
					array(
						'label'	=> 'Delete', 
						'uri'	=> '/journal/delete/' . $this -> journal[ 'id' ]
					), 
					array(
						'label'	=> 'Edit', 
						'uri'	=> '/journal/edit/' . $this -> journal[ 'id' ]
					)
				)
			)
		);
	
	?>
	
	 <div class="span9">
		 <div class="content">
			 <div class="article">     
			 
			 	<h1>Registration</h1>
			 
				<?= $this -> form; ?>
				
			 </div>
		</div>
	</div>
 
</div>