<!DOCTYPE html>
<!-- saved from url=(0041)http://demo.webinby.ru/responsivedesign/# -->
<html lang="ru"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     

<link rel="stylesheet" href="/bootstrap/bootstrap.css" type="text/css">
<link rel="stylesheet" href="/bootstrap/style.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="http://demo.webinby.ru/responsivedesign/css/bootstrap-responsive.css" rel="stylesheet">
<title>Responsive Design Twitter Bootstrap</title>
<!-- Dynamic styles -->
		<?= $this -> headLink(); ?>
				
		<!-- Dynamic JS -->
		<?= $this -> headScript(); ?>

    <script type = "text/javascript" 
			src = "/client/application/views/scripts/authorization/registration.js">
		</script>
    </head>
<body>
<div class="container">
<div class="row">
<div class="span12">
<div id="header">
 <div class="row">
     <div class="span2" ><img src="/img/pu.png"></div>
      <div class="span8"><div id="logo"><b>Кафедра диференціальних рівнянь та прикладної математики</b></div></div>
      <div class="span2" ><img src="/img/mif.png"></div>
  </div>
</div>
</div>
</div>
<div class="padding-top">
<div class="row">
 <div class="span12">
 <div class="navigation hidden-phone">
  <div class="navbar">
  <div class="navbar-inner">
    <a class="brand hidden-phone" href="./Responsive Design Twitter Bootstrap_files/Responsive Design Twitter Bootstrap.htm"><i class="icon-home"></i></a>
    <ul class="nav">
      <li class="active"><a href="#">Link1</a></li>
      <li class="divider-vertical"></li>
      <li><a href="#">Link2</a></li>
      <li class="divider-vertical"></li>
      <li><a href="#">Link3</a></li>
        <li class="divider-vertical hidden-phone"></li>
    </ul>
    
    <form class="form-search">
  <div class="input-append">
    <input type="text" class="span2 search-query">
    <button type="submit" class="btn">Search</button>
  </div>
  </form>
  </div>
</div>
</div>
   <div class="mobile-navigation hidden-tablet hidden-desktop">
   <select data-rt-menu-mobile="">
									<option value="/link/" selected="selected"> Home</option>

																<option value="/link/" selected="selected"> Linkm1</option>

									<option value="/link/" selected="selected"> Link</option>
													<option value="/link/" selected="selected"> Linkm2</option>

												<option value="/link/" selected="selected"> Linkm3</option>

									<option value="/link/" selected="selected"> Link</option>
													<option value="/link/" selected="selected"> Linkm4</option>



														</select>
														</div>
</div>
</div>

</div>
<div class="padding-top">

    
     <?php echo $this->layout()->content; ?>
    
<div class="padding-top">
<div class="row">
 <div class="span12">
 <div id="footer">
     <div class="copyright"> Web Development by: <br>
         <a href="http://vk.com/weber89"><span style="color: red;">A</span>ndriy Khristonko</a><br>
         <a href="http://vk.com/coffeine_009"><span style="color: red;">V</span>italiy Tsutsman</a><br>
         <a href="http://vk.com/id41445479"><span style="color: red;">A</span>ndriy Pliasun</a>
 </div>
</div>
</div>
</div>
</div>



</div></div></body></html>
