<html>

	<head>
	
	
	
		<title>DEAM</title>
		
		<link type = "text/css" rel = "stylesheet"
			href = "/client/application/views/styles/authorization/registration.css"
		/>
		<!-- 
		<script type = "text/javascript" 
			src = "/client/application/views/scripts/authorization/registration.js">
		</script>-->
	
	</head>
	
	<body>

		<h1>OK</h1>

		<div style = "border: solid 1px #000; background:#eee;">
			<?php echo $this->layout()->content; ?>
		</div>
	
	</body>
	
</html>